<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Extend the `sync_state` enum on `service_reports` to allow
 * `discarded`. SQLite stores enum columns as TEXT with an implicit
 * CHECK constraint generated by `$table->enum(...)`. SQLite has no
 * `ALTER TABLE ... MODIFY COLUMN`, so the portable path is to
 * rebuild the table with the corrected CHECK clause and copy the
 * data across.
 *
 * Why `discarded` exists:
 *   Some rows will never sync — typically because the source ticket
 *   has been moved to monday trash (validation code
 *   `linkedToDeletedItems`), or because they were created by
 *   interrupted test scripts that left behind rows with invalid
 *   `tsp_workwith_person_ids`. The drainer keeps retrying them and
 *   the dashboard banner keeps nagging the user. The fix is for the
 *   user (or an admin) to mark the row as `discarded` and stop
 *   showing it in the banner.
 */
return new class extends Migration {
    public function up(): void
    {
        // 1) Read the original CREATE TABLE statement. We need its
        //    full column list, indexes, and FKs, with only the
        //    CHECK constraint on sync_state modified.
        $row = DB::selectOne(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='service_reports'"
        );
        if (! $row || ! $row->sql) {
            throw new \RuntimeException(
                'Could not find service_reports table to migrate sync_state enum.'
            );
        }
        $originalSql = $row->sql;

        // sqlite_master stores the full "CREATE TABLE name (cols)"
        // statement. We only need the inner column list.
        if (! preg_match('/^CREATE TABLE\s+"?\w+"?\s*\((.*)\)\s*$/s', $originalSql, $m)) {
            throw new \RuntimeException(
                'Could not parse CREATE TABLE statement: ' . $originalSql
            );
        }
        $columnList = $m[1];

        $newColumnList = preg_replace(
            '/check \("sync_state" in \([\'"]pending[\'"], [\'"]syncing[\'"], [\'"]synced[\'"], [\'"]error[\'"]\)\)/i',
            "check (\"sync_state\" in ('pending','syncing','synced','error','discarded'))",
            $columnList
        );
        if ($newColumnList === $columnList) {
            throw new \RuntimeException(
                'Failed to update sync_state CHECK constraint in CREATE TABLE statement. '
                . 'Column list: ' . $columnList
            );
        }

        // 2) Rebuild the table. The pattern is:
        //    - create a copy with the new schema
        //    - copy all rows
        //    - drop the original
        //    - rename the copy
        // Foreign keys are temporarily disabled to avoid cascading
        // deletes breaking the rebuild.
        DB::statement('PRAGMA foreign_keys=OFF');
        DB::transaction(function () use ($newColumnList) {
            DB::statement("CREATE TABLE service_reports__new ({$newColumnList})");
            DB::statement('INSERT INTO service_reports__new SELECT * FROM service_reports');
            DB::statement('DROP TABLE service_reports');
            DB::statement('ALTER TABLE service_reports__new RENAME TO service_reports');
        });
        DB::statement('PRAGMA foreign_keys=ON');
    }

    public function down(): void
    {
        // No down-migration: going from discarded back to one of
        // the original four values would lose information. If you
        // really need to roll back, restore from backup.
        throw new \RuntimeException(
            'This migration cannot be reversed. Restore from backup if you need to roll back.'
        );
    }
};
