<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

/**
 * A single-use registration token for a customer who appears on the
 * monday.com Customer Details board.
 *
 * Generated by the `portal:invite-customer` artisan command. Spent
 * by the registration form at /register/{token}. Never reused.
 *
 * @property int    $id
 * @property string $token               URL-safe random token
 * @property string $email               Customer email (snapshot)
 * @property string $account_name        Hospital / account name (snapshot)
 * @property string $branch              Branch label (snapshot, e.g. "NCR - NATIONAL CAPITAL REGION")
 * @property string|null $region         Region label (snapshot, e.g. "NCR")
 * @property string|null $address        Free-text address (snapshot)
 * @property string|null $monday_customer_id  Monday item id for cross-reference
 * @property Carbon|null $expires_at
 * @property Carbon|null $used_at
 * @property int|null    $used_by_user_id
 * @property int|null    $invited_by_user_id
 * @property Carbon $created_at
 * @property Carbon $updated_at
 */
class CustomerInvite extends Model
{
    protected $fillable = [
        'token', 'email', 'account_name', 'branch', 'region', 'address',
        'monday_customer_id', 'expires_at', 'used_at',
        'used_by_user_id', 'invited_by_user_id',
    ];

    protected $casts = [
        'expires_at' => 'datetime',
        'used_at'    => 'datetime',
    ];

    /**
     * Default token lifetime: 14 days. Long enough that a customer
     * can ignore a forwarded email for a weekend but short enough
     * that stale tokens don't pile up.
     */
    public const DEFAULT_TTL_DAYS = 14;

    // -----------------------------------------------------------------
    // Token generation
    // -----------------------------------------------------------------

    /**
     * Generate a new cryptographically-random token. 32 bytes of
     * randomness is more than enough — even at 1000 invites/sec
     * the collision probability is astronomically low.
     */
    public static function generateToken(): string
    {
        return rtrim(strtr(base64_encode(random_bytes(32)), '+/', '-_'), '=');
    }

    // -----------------------------------------------------------------
    // Lookups
    // -----------------------------------------------------------------

    /**
     * Find an invite by its token, scoped to those that are still
     * usable (not used, not expired).
     */
    public static function findUsable(string $token): ?self
    {
        return static::query()
            ->where('token', $token)
            ->whereNull('used_at')
            ->where(function (Builder $q) {
                $q->whereNull('expires_at')
                  ->orWhere('expires_at', '>', now());
            })
            ->first();
    }

    // -----------------------------------------------------------------
    // Status helpers
    // -----------------------------------------------------------------

    public function isUsed(): bool
    {
        return $this->used_at !== null;
    }

    public function isExpired(): bool
    {
        return $this->expires_at !== null && $this->expires_at->isPast();
    }

    public function isUsable(): bool
    {
        return ! $this->isUsed() && ! $this->isExpired();
    }

    // -----------------------------------------------------------------
    // Spending
    // -----------------------------------------------------------------

    /**
     * Mark the token as spent. Called from the registration handler
     * AFTER the user is created, so a failed registration doesn't
     * lock out a legitimate customer.
     */
    public function markUsed(int $userId): void
    {
        $this->forceFill([
            'used_at'         => now(),
            'used_by_user_id' => $userId,
        ])->save();
    }

    // -----------------------------------------------------------------
    // Relations
    // -----------------------------------------------------------------

    public function invitedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'invited_by_user_id');
    }

    public function usedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'used_by_user_id');
    }
}
